METHOD_ICA = "ICA"
METHOD_DICTIONARY_LEARNING = "DICT"
CLUSTERING_SVM = "SVM"
CLUSTERING_RNN = "RNN"
CLUSTERING_TRANSFORMERS = "TR"

NUM_IMAGES_FOR_COMPONENTS = 10
NUM_COMPONENTS = 20
STANDARDIZE = True
LOW_PASS = 0.08
HIGH_PASS = 0.01

